<?php

namespace App\Filament\Resources\Loans\Schemas;

use App\Models\Asset;
use App\Enums\LoanStatus;
use App\Enums\AssetStatus;
use App\Enums\ProductType;
use Filament\Schemas\Schema;
use App\Models\ConsumableStock;
use Filament\Schemas\Components\Grid;
use Illuminate\Support\Facades\Auth;
use Filament\Forms\Components\Hidden;
use Filament\Forms\Components\Select;
use Filament\Schemas\Components\Section;
use Filament\Forms\Components\Repeater;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\DateTimePicker;
use App\Filament\Resources\Loans\Pages\CreateLoan;

class LoanForm
{

    /**
     * Configure the form schema.
     *
     * This form uses a "Hybrid Architecture" to handle the complex polymorphic nature
     * of LoanItems (Assets vs Consumables).
     *
     * 1. On Edit/View: It behaves like a standard Filament Relationship Repeater.
     * 2. On Create: It disables the relationship binding. The data is processed
     *    manually in `CreateLoan::handleRecordCreation` to ensure robust persistence.
     *
     * @param Schema $schema
     * @return Schema
     */
    public static function configure(Schema $schema): Schema
    {
        // Check if form should be read-only (only Pending loans are editable)
        $isReadOnly = function ($livewire) {
            $record = $livewire->getRecord();
            return $record && $record->status !== LoanStatus::Pending;
        };

        return $schema
            ->components([
                Section::make(__('resources.loans.fields.loan_info'))
                    ->schema([
                        // Hidden Auto-filled fields
                        Hidden::make('user_id')
                            ->default(fn() => Auth::id())
                            ->required(),

                        // Code is generated by LoanObserver, but displayed here for context.
                        TextInput::make('code')
                            ->label(__('resources.loans.fields.code'))
                            ->disabled()
                            ->dehydrated()
                            ->maxLength(32)
                            ->columnSpanFull()
                            ->visible(fn($record) => $record !== null),

                        TextInput::make('borrower_name')
                            ->label(__('resources.loans.fields.borrower'))
                            ->required()
                            ->maxLength(255)
                            ->placeholder(__('resources.loans.fields.borrower_placeholder'))
                            ->disabled(fn($livewire) => $isReadOnly($livewire))
                            ->columnSpanFull(),

                        DateTimePicker::make('loan_date')
                            ->label(__('resources.loans.fields.loan_date'))
                            ->default(now())
                            ->required()
                            ->native(false)
                            ->disabled(fn($livewire) => $isReadOnly($livewire)),

                        DateTimePicker::make('due_date')
                            ->label(__('resources.loans.fields.due_date'))
                            ->default(now()->addDays(1))
                            ->required()
                            ->native(false)
                            ->afterOrEqual('loan_date')
                            ->disabled(fn($livewire) => $isReadOnly($livewire)),

                        Textarea::make('purpose')
                            ->label(__('resources.loans.fields.purpose'))
                            ->required()
                            ->rows(2)
                            ->columnSpanFull()
                            ->disabled(fn($livewire) => $isReadOnly($livewire)),

                        Textarea::make('notes')
                            ->label(__('resources.loans.fields.notes'))
                            ->rows(2)
                            ->columnSpanFull()
                            ->disabled(fn($livewire) => $isReadOnly($livewire)),

                        FileUpload::make('proof_image')
                            ->label(__('resources.loans.fields.proof_image'))
                            ->image()
                            ->disk('public')
                            ->directory('loan-proofs')
                            ->visibility('public')
                            ->maxSize(5120) // 5MB
                            ->disabled(fn($livewire) => $isReadOnly($livewire))
                            ->columnSpanFull(),
                    ])
                    ->columns(2),

                Section::make(__('resources.loans.fields.items_list'))
                    ->description(__('resources.loans.fields.items_list_desc'))
                    ->schema([
                        Repeater::make('loanItems')
                            ->label('')
                            // HYBRID ARCHITECTURE:
                            // We disable the 'relationship' method specifically on the Create page.
                            // This allows us to receive the raw 'loanItems' array in the Controller
                            // and process it manually, bypassing Filament's hydration complexities
                            // for this polymorphic form.
                            ->when(
                                !($schema->getLivewire() instanceof CreateLoan),
                                fn($component) => $component->relationship()
                            )
                            ->schema([
                                Grid::make(1)->schema([
                                    // Unified Selection Field (Virtual)
                                    // This field drives the population of the hidden 'type' and ID fields.
                                    Select::make('item_selection')
                                        ->label(__('resources.loans.fields.item_selection'))
                                        ->searchable()
                                        ->getSearchResultsUsing(function (string $search) {
                                            $results = [];
                                            $assetLabel = __('resources.loans.fields.type_asset');
                                            $stockLabel = __('resources.loans.fields.type_stock');

                                            // Search Assets (In Stock)
                                            $assets = Asset::where('status', AssetStatus::InStock)
                                                ->where(fn($q) => $q->where('asset_tag', 'like', "%{$search}%")
                                                    ->orWhereHas('product', fn($sq) => $sq->where('name', 'like', "%{$search}%")))
                                                ->with(['product', 'location'])
                                                ->limit(25)
                                                ->get();

                                            foreach ($assets as $asset) {
                                                $site = $asset->location?->site?->value ?? '-';
                                                $productName = $asset->product?->name ?? __('resources.loans.fields.unknown_product');
                                                $label = "{$productName} ({$assetLabel}: {$asset->asset_tag}) | {$asset->location?->name} ({$site})";
                                                $results["asset_{$asset->id}"] = $label;
                                            }

                                            // Search Consumables (Has Stock)
                                            $consumables = ConsumableStock::where('quantity', '>', 0)
                                                ->whereHas('product', fn($q) => $q->where('name', 'like', "%{$search}%"))
                                                ->with(['product', 'location'])
                                                ->limit(25)
                                                ->get();

                                            foreach ($consumables as $stock) {
                                                $site = $stock->location?->site?->value ?? '-';
                                                $productName = $stock->product?->name ?? __('resources.loans.fields.unknown_product');
                                                $label = "{$productName} ({$stockLabel}: {$stock->quantity}) | {$stock->location?->name} ({$site})";
                                                $results["consumable_{$stock->id}"] = $label;
                                            }

                                            return $results;
                                        })
                                        ->getOptionLabelUsing(function ($value) {
                                            if (!$value) return null;
                                            [$type, $id] = explode('_', $value);
                                            $assetLabel = __('resources.loans.fields.type_asset');
                                            $stockLabel = __('resources.loans.fields.type_stock');

                                            if ($type === 'asset') {
                                                $asset = Asset::with(['product', 'location'])->find($id);
                                                $site = $asset?->location?->site?->value ?? '-';
                                                $productName = $asset->product?->name ?? __('resources.loans.fields.unknown_product');
                                                return $asset ? "{$productName} ({$assetLabel}: {$asset->asset_tag}) | {$asset->location?->name} ({$site})" : null;
                                            } else {
                                                $stock = ConsumableStock::with(['product', 'location'])->find($id);
                                                $site = $stock?->location?->site?->value ?? '-';
                                                $productName = $stock->product?->name ?? __('resources.loans.fields.unknown_product');
                                                return $stock ? "{$productName} ({$stockLabel}: {$stock->quantity}) | {$stock->location?->name} ({$site})" : null;
                                            }
                                        })
                                        ->required()
                                        ->live()
                                        ->afterStateUpdated(function ($set, $state) {
                                            if (!$state) {
                                                $set('type', null);
                                                $set('asset_id', null);
                                                $set('consumable_stock_id', null);
                                                return;
                                            }

                                            [$typeStr, $id] = explode('_', $state);

                                            if ($typeStr === 'asset') {
                                                $set('type', ProductType::Asset->value);
                                                $set('asset_id', $id);
                                                $set('consumable_stock_id', null);
                                                $set('quantity_borrowed', 1);
                                            } else {
                                                $set('type', ProductType::Consumable->value);
                                                $set('asset_id', null);
                                                $set('consumable_stock_id', $id);
                                            }
                                        })
                                        ->afterStateHydrated(function ($component, $record) {
                                            if ($record) {
                                                if ($record->type === ProductType::Asset) {
                                                    $component->state("asset_{$record->asset_id}");
                                                } else {
                                                    $component->state("consumable_{$record->consumable_stock_id}");
                                                }
                                            }
                                        })
                                        ->dehydrated(false) // Virtual field
                                        ->disabled(fn($livewire) => $isReadOnly($livewire)),

                                    // Hidden Fields to Store Type & IDs
                                    // These MUST be present for CreateLoan to function, as it reads from the validated data.
                                    Hidden::make('type')->required(),
                                    Hidden::make('asset_id'),
                                    Hidden::make('consumable_stock_id'),

                                    // Quantity
                                    TextInput::make('quantity_borrowed')
                                        ->label(__('resources.loans.fields.quantity'))
                                        ->numeric()
                                        ->default(1)
                                        ->minValue(1)
                                        ->maxValue(function ($get) {
                                            $type = $get('type');
                                            if ($type === ProductType::Consumable->value) {
                                                $stockId = $get('consumable_stock_id');
                                                if ($stockId) {
                                                     return ConsumableStock::find($stockId)?->quantity ?? 1;
                                                }
                                            }
                                            return 1; // Asset always 1
                                        })
                                        ->readOnly(fn($get) => $get('type') === ProductType::Asset->value)
                                        ->required()
                                        ->disabled(fn($livewire) => $isReadOnly($livewire))
                                        ->columnSpanFull(),
                                ]),
                            ])
                            ->defaultItems(1)
                            ->columns(1)
                            ->addActionLabel(__('resources.loans.actions.add_item'))
                            ->deletable(fn($livewire) => !$isReadOnly($livewire))
                            ->addable(fn($livewire) => !$isReadOnly($livewire))
                            ->disabled(fn($livewire) => $isReadOnly($livewire)),
                    ]),
            ]);
    }
}
